### ISSUE TITLE
I don't seem to have editing access, so I forked it. Whoever has edit rights, please merge these

### ISSUE THREAD

**Issue by aashish-khub** [ossd-sp22/ColoredMeValentined#2]
I have made edits and added documentation but it wouldn't let me merge them. So I have forked the repo and added my changes to that. You can find it here: https://github.com/aashish-khub/ColoredMeValentined

I will be busy in the afternoon so whoever has access, please merge my edits with this one.

**Comment by tangym27** [comment]
Sorry about that – fixed!
